Better handle errors in FsImageContainer.open_archive()
Under some conditions GuestFS.launch() can fail.
For example under Ubuntu 17.04 the linux kernel images under /boot/
are only readable by root.
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/759725

The failure is handled in open_archive but extract and
close_archive are still called and do not handle the half initialized
FsImageContainer.

They throw the following exceptions when called:
RuntimeError: tar_out: call launch before using this function.
RuntimeError: umount_all: call launch before using this function

Avoid this problem the following way:
* If starting guestfs fails, raise a ContainerExtractionError.
  This will cause the image to be compared as a raw file without
  calling any other container extraction methods.
  It will also leave information about the failed extraction in the result.
* If guestfs is not available, return an empty array from get_member_names.
  This will cause the image to be compared as a raw file.
  It would be nice to raise a RequiredToolNotFound in this case
  but currently it supports missing tools, but not missing python modules.

This should help with
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=837681